extends "res://scripts/test_support/test_case.gd"

# THE RACE CIRCUIT. M26 phase 1 -- see implementation_plans/m26_race_track.md.
#
# A closed ring with a hole in the middle, generated by the same rolled-band
# pattern as the serpentine. Nothing drives on it yet; this file is the oracle
# that says it is a circuit at all.
#
# THE VALIDATOR CANNOT ASK THIS QUESTION. `SegmentValidator` models a walking
# player crossing from entry to exit, which is exactly right for a corridor and
# meaningless here: a loop is crossable through EITHER half of the ring, so a
# circuit with its middle filled in solid validates perfectly and is not a
# circuit. M25 said every mode would eventually need a traversal oracle of its
# own; this is the first one that really does.
#
# THE CLAIM IS AN ENCLOSURE, NOT A MEASUREMENT. "The road goes round" invites a
# threshold -- how round, how wide, how many corners. "You cannot reach the
# middle from outside without crossing road" is a fact about a flood fill: it is
# true or it is not, it fails loudly the moment a corner is cut through, and no
# amount of tuning can make a broken circuit satisfy it.
#
# The claims:
#   1. THERE IS AN INFIELD AT ALL. A solid section is not a bad circuit, it is
#      not a circuit -- and it is the absence-shaped failure this project keeps
#      being caught by, so it is asserted first and as a presence.
#   2. THE ROAD ENCLOSES IT. Flood from outside; the middle must be unreachable.
#   3. THE ROAD IS A SINGLE RING. Flood the road itself from one cell: all of it
#      must be reachable, or the circuit is two arcs and a gap.
#   4. IT IS WIDE ENOUGH TO DRIVE. Every side at least RACE_LANE_MIN, measured
#      off the geometry rather than off the constants that made it.
#   5. THE GATES GO ROUND IN ORDER, one per side, each spanning its own road, and
#      none of them in the infield.
#   6. AND CIRCUITS DIFFER. Same trap as the serpentine's first draft, where the
#      seed chose one bit and three sections came out identical.

const GridConfig = preload("res://scripts/grid/grid_config.gd")
const SegmentGen = preload("res://scripts/grid/segment_gen.gd")

# BOTH CANVASES, and the narrow one is not padding.
#
# At 21 the two facing sides can be at their widest (7 + 7) and still leave an
# infield (21 - 6), so the clamp that stops them meeting NEVER FIRES -- A/B'd,
# and removing it changed not one cell. A guard nothing exercises is a guard
# nobody knows is broken. At 15 the same roll overruns by five, so the clamp is
# the only thing standing between a rolled circuit and a solid field.
const WIDTHS := [21, 15]
const SEEDS := 40

var done := false

func setup(_main) -> void:
	timeout_seconds = 40.0

func _physics_process(_delta: float) -> void:
	if done:
		return
	done = true
	_it_is_a_ring_with_a_hole_in_it()
	_the_gates_go_round_in_order()
	_no_two_circuits_are_the_same()
	_a_circuit_is_not_a_rectangle()
	_every_circuit_type_is_built_and_is_different()
	_the_road_width_varies_enough_to_force_a_lift()
	finish()

func _it_is_a_ring_with_a_hole_in_it() -> void:
	var enclosed := 0
	var leaked := 0
	var solid := 0
	var split := 0
	var narrow := 0
	var thinnest := 999
	var slots := 0
	var pinched := 999
	# ONE LOOP OVER BOTH CANVASES. Flattened rather than nested because GDScript
	# is indentation-sensitive and a nested sweep here buys nothing but a level.
	for i in WIDTHS.size() * SEEDS:
		var w: int = int(WIDTHS[i / SEEDS])
		var seed_value: int = i % SEEDS
		var seg = SegmentGen.race_loop(w, seed_value, seed_value % 5)
		var holes: int = _count(seg, false)
		if holes == 0:
			solid += 1
			continue
		# 2. FLOOD THE VOID FROM OUTSIDE. Every hole cell reachable from beyond
		# the canvas is outside the ring; anything left over is infield. A
		# circuit has leftovers.
		var outside: Dictionary = _flood_void_from_edge(seg)
		var inside := 0
		for z in seg.length:
			for x in seg.width:
				if not seg.is_solid(x, z) and not outside.has(Vector2i(x, z)):
					inside += 1
		if inside == 0:
			leaked += 1
		else:
			enclosed += 1
		# 4b. AND THE HOLE IS A HOLE, not a slot. Enclosure alone does not care how
		# big the middle is -- a one-cell-wide gutter down the centre is perfectly
		# enclosed and is a thick border with a crack in it. This is what the
		# facing-sides clamp in the generator is actually FOR, and without this
		# claim removing that clamp changed nothing any assertion could see.
		var span: Vector2i = _infield_span(seg, outside)
		pinched = mini(pinched, mini(span.x, span.y))
		if mini(span.x, span.y) < SegmentGen.RACE_INFIELD_MIN:
			slots += 1
		# 3. And the road is ONE ring rather than two arcs.
		if not _road_is_connected(seg):
			split += 1
		# 4. Wide enough on every side, measured off the geometry.
		var side: int = _thinnest_side(seg)
		thinnest = mini(thinnest, side)
		if side < SegmentGen.RACE_LANE_PINCH:
			narrow += 1
	print("[race] %d circuits: %d enclosed, %d leaked, %d solid, %d split, %d narrow (thinnest side %d)"
		% [WIDTHS.size() * SEEDS, enclosed, leaked, solid, split, narrow, thinnest])
	print("[race] infield: %d pinched below %d cells (tightest %d)"
		% [slots, SegmentGen.RACE_INFIELD_MIN, pinched])

	# THE PRESENCE CLAIM FIRST. A generator that produced nothing at all would
	# satisfy every correctness assertion below it.
	check(enclosed > 0,
		"circuits are generated at all (%d of %d)"
			% [enclosed, WIDTHS.size() * SEEDS])
	eq(solid, 0,
		"no section comes out solid (%d) -- a circuit with its middle filled in "
			% solid
		+ "is not a bad circuit, it is a field, and it would pass the ordinary "
		+ "validator without complaint")
	eq(leaked, 0,
		"and the road encloses the infield on every one of them (%d leaked) -- "
			% leaked
		+ "flooded from outside the canvas, the middle is unreachable without "
		+ "crossing road. That is what makes the ring a ROUTE rather than a "
		+ "racing line somebody could cut across")
	eq(split, 0,
		"the road is a single connected ring (%d split) -- two arcs and a gap "
			% split
		+ "encloses an infield just as well and is not a circuit")
	eq(narrow, 0,
		"and no piece of road is narrower than the pinch (%d too thin, thinnest "
			% narrow
		+ "%d of %d) -- two cells is 4 m against a 1.1 m bus, which is a squeeze "
			% [thinnest, SegmentGen.RACE_LANE_PINCH]
		+ "you slow for. One cell is 45 cm of clearance, which is a wall")
	eq(slots, 0,
		"and the infield is at least %d cells across in both directions (%d "
			% [SegmentGen.RACE_INFIELD_MIN, slots]
		+ "pinched, tightest %d) -- an enclosed one-cell gutter is a thick border "
			% pinched
		+ "with a crack in it, and it is the only thing the facing-sides clamp "
		+ "exists to prevent")

func _the_gates_go_round_in_order() -> void:
	var seen_all := 0
	var in_void := 0
	var out_of_order := 0
	var leaky_gate := 0
	var along := 0
	# ONE LOOP OVER BOTH CANVASES. Flattened rather than nested because GDScript
	# is indentation-sensitive and a nested sweep here buys nothing but a level.
	for i in WIDTHS.size() * SEEDS:
		var w: int = int(WIDTHS[i / SEEDS])
		var seed_value: int = i % SEEDS
		var seg = SegmentGen.race_loop(w, seed_value, seed_value % 5)
		var by_index := {}
		var last := -1
		for entry in seg.checker_cells:
			var cell: Vector2i = entry[0]
			var idx: int = int(entry[1])
			by_index[idx] = int(by_index.get(idx, 0)) + 1
			# A GATE IN THE HOLE IS A GATE NOBODY CAN CROSS, which is the failure
			# that looks like a lap counter that never advances.
			if not seg.is_solid(cell.x, cell.y):
				in_void += 1
			# Recorded in walking order, so the mode can say `the next one` and
			# never has to know the shape of the circuit.
			if idx < last:
				out_of_order += 1
			last = idx
		if by_index.size() == SegmentGen.RACE_CHECKPOINTS:
			seen_all += 1
		# YOU CANNOT DRIVE AROUND A GATE, and that is the whole claim.
		#
		# The obvious assertion is about ORIENTATION -- is this gate a row or a
		# column -- and it is a trap, because "across" is different on every side
		# of a ring. This got written wrong TWICE in opposite directions: first
		# the side gates ran down their straights, then the fix put the start line
		# along the north straight instead of across it. Both times all four gates
		# were present, none in the void, all in order, everything green.
		#
		# So ask the property that matters instead: step one cell past either end
		# of the gate and you must be OFF THE ROAD. A stripe fails it because its
		# ends run into the corners; a gate covering half the road fails it; and it
		# needs to know nothing about which way anything is pointing, which is why
		# it survives a circuit that is not a rectangle.
		for idx in by_index.keys():
			if not _gate_spans_the_road(seg, idx):
				leaky_gate += 1
			# AND ONE CELL THICK IN THE DIRECTION YOU TRAVEL, which is the half
			# the rule above cannot see.
			#
			# A start line laid ALONG the north straight spans the whole canvas,
			# so its ends run off the edge and "you cannot drive around it" is
			# perfectly true -- you drive ALONG it, for twenty-one cells, and a
			# lap gate you are inside for a whole straight fires continuously.
			# A/B'd: that exact bug passed the rule above.
			#
			# The road at a gate is a corridor, and a corridor has a narrow axis.
			# A gate belongs on the NARROW one. That is orientation stated without
			# ever naming a direction, so it reads the same on a straight, on a
			# corner, and on whatever shape a circuit grows next.
			if not _gate_is_a_crossing(seg, idx):
				along += 1
	print("[race] gates: %d drivable around, %d laid along the road"
		% [leaky_gate, along])
	print("[race] gates: %d of %d sections carry all %d, %d in void, %d out of order"
		% [seen_all, WIDTHS.size() * SEEDS, SegmentGen.RACE_CHECKPOINTS, in_void, out_of_order])

	eq(seen_all, WIDTHS.size() * SEEDS,
		"every circuit carries all %d gates (%d of %d) -- a lap you cannot "
			% [SegmentGen.RACE_CHECKPOINTS, seen_all, WIDTHS.size() * SEEDS]
		+ "complete is worse than no lap timing, because it looks like the timer "
		+ "is broken rather than the track")
	eq(in_void, 0, "and none of them sits over the hole (%d)" % in_void)
	eq(leaky_gate, 0,
		"and no gate can be driven around (%d) -- one cell past either end has to "
			% leaky_gate
		+ "be off the road, or a lap can be taken without crossing it and the "
		+ "sequence means nothing")
	eq(along, 0,
		"and no gate is longer than a road is wide (%d too long) -- a gate you "
			% along
		+ "drive down the LENGTH of is one you are inside for a whole straight, "
		+ "and that is the half `driven around` cannot see: a stripe spanning the "
		+ "full canvas has both ends off the map, so it satisfies that rule while "
		+ "being exactly the wrong shape")
	eq(out_of_order, 0,
		"and they are recorded in the order they are driven through (%d out of "
			% out_of_order
		+ "sequence), so `the next one` is +1 and the mode never infers an order "
		+ "from geometry")

func _no_two_circuits_are_the_same() -> void:
	# THE SERPENTINE'S FIRST DRAFT ROLLED ONE BIT and produced three identical
	# sections, which nobody noticed until they were drawn side by side. Same
	# generator pattern here, so the same claim -- and stated as a COUNT OF
	# DISTINCT SHAPES rather than as "they look different".
	var shapes := {}
	# ONE LOOP OVER BOTH CANVASES. Flattened rather than nested because GDScript
	# is indentation-sensitive and a nested sweep here buys nothing but a level.
	for i in WIDTHS.size() * SEEDS:
		var w: int = int(WIDTHS[i / SEEDS])
		var seed_value: int = i % SEEDS
		var seg = SegmentGen.race_loop(w, seed_value, seed_value % 5)
		shapes[_signature(seg)] = true
	print("[race] %d distinct circuits from %d rolls" % [shapes.size(), WIDTHS.size() * SEEDS])
	check(shapes.size() >= SEEDS / 3,
		"circuits differ from one another (%d distinct shapes in %d seeds) -- the "
			% [shapes.size(), WIDTHS.size() * SEEDS]
		+ "four sides are rolled separately, so a track has a character rather "
		+ "than being a rounded rectangle with the numbers changed")

# --- Instruments --------------------------------------------------------------

# WHETHER A GATE REALLY BLOCKS THE ROAD IT SITS ON. Its cells form a line; the
# cell one step beyond each end, along that line, must not be road.
#
# Orientation is DERIVED from the cells rather than assumed, so this asks the
# same question of a gate on a straight and a gate on a corner -- which is what
# makes it survive the day a circuit stops being a rectangle.
func _gate_spans_the_road(seg, idx: int) -> bool:
	var cells: Array = []
	for entry in seg.checker_cells:
		if int(entry[1]) == idx:
			cells.append(entry[0] as Vector2i)
	if cells.is_empty():
		return false
	var rows := {}
	var cols := {}
	for c in cells:
		rows[c.y] = true
		cols[c.x] = true
	var step := Vector2i(1, 0) if rows.size() == 1 else Vector2i(0, 1)
	if rows.size() != 1 and cols.size() != 1:
		return false          # not a line at all
	var lo: Vector2i = cells[0]
	var hi: Vector2i = cells[0]
	for c in cells:
		if c.x * step.x + c.y * step.y < lo.x * step.x + lo.y * step.y:
			lo = c
		if c.x * step.x + c.y * step.y > hi.x * step.x + hi.y * step.y:
			hi = c
	for beyond in [lo - step, hi + step]:
		if beyond.x < 0 or beyond.x >= seg.width or beyond.y < 0 or beyond.y >= seg.length:
			continue          # the canvas edge is as good as a wall
		if seg.is_solid(beyond.x, beyond.y):
			return false
	return true

# THE SHAPE CLAIM, AND IT IS A PROOF RATHER THAN A THRESHOLD.
#
# "Interesting" is not testable and "the corners are good" is not either. But a
# RECTANGLE'S INFIELD EDGE TAKES EXACTLY ONE VALUE -- that is what makes it a
# rectangle -- so an edge that takes three is arithmetically not one, whatever
# else it is. Same shape of claim as the bridge's even-width proof in M22: find
# the thing the old code COULD NOT PRODUCE and assert that.
#
# Asserted on the majority rather than on every circuit, because a roll is
# allowed to come up nearly straight now and then; a fast circuit among twisty
# ones is variety, and demanding every one bend would be tuning the roll through
# the test.
func _a_circuit_is_not_a_rectangle() -> void:
	var bent := 0
	var widest_swing := 0
	for i in WIDTHS.size() * SEEDS:
		var w: int = int(WIDTHS[i / SEEDS])
		var seg = SegmentGen.race_loop(w, i % SEEDS, (i % SEEDS) % 5)
		var edges := {}
		var lo := 999
		var hi := -1
		for z in seg.length:
			var edge: int = _left_edge_of_infield(seg, z)
			if edge < 0:
				continue
			edges[edge] = true
			lo = mini(lo, edge)
			hi = maxi(hi, edge)
		if edges.size() >= 3:
			bent += 1
		if hi >= 0:
			widest_swing = maxi(widest_swing, hi - lo)
	print("[race] %d of %d circuits bend (widest infield swing %d cells)"
		% [bent, WIDTHS.size() * SEEDS, widest_swing])
	check(bent > WIDTHS.size() * SEEDS / 2,
		"most circuits bend (%d of %d) -- a rectangle's infield edge takes "
			% [bent, WIDTHS.size() * SEEDS]
		+ "exactly ONE value down the whole track, so three distinct values is a "
		+ "proof that the shape is not one. Without this, a regression to the "
		+ "rounded rectangle it started as passes every other claim in the file")
	check(widest_swing >= 4,
		"and the hole really crosses the canvas (%d cells at its widest) -- a "
			% widest_swing
		+ "swing of one is a wobble, and the point is that the road PINCHES on "
		+ "one rail while it opens on the other")

# ALL FOUR CHARACTERS, AND EACH ONE RECOGNISABLE FROM THE GEOMETRY.
#
# THE PRESENCE HALF FIRST. A character that is rolled and never produced is the
# absence-shaped failure this project keeps being caught by, and it would leave
# every claim below true of an empty set. The serpentine's lane flavours were
# checked the same way and for the same reason.
#
# THE RECOGNITION HALF IS DELIBERATELY NOT "does it look right". Each kind is
# identified by a property the OTHERS do not have:
#   HAIRPIN     one side is at its minimum for a long unbroken stretch.
#   BOTTLENECK  some row has BOTH sides at their minimum at once -- the one shape
#               with no wide line anywhere, which is what makes it a bottleneck.
#   CHICANE     the hole reverses direction three times or more.
# An oval has none of those, which is what an oval is.
func _every_circuit_type_is_built_and_is_different() -> void:
	var seen := {}
	var hairpin_long := 0
	var bottleneck_squeeze := 0
	var chicane_kinks := 0
	for i in WIDTHS.size() * SEEDS:
		var w: int = int(WIDTHS[i / SEEDS])
		var seg = SegmentGen.race_loop(w, i % SEEDS, (i % SEEDS) % 5)
		var kind := -1
		for k in SegmentGen.CIRCUIT_KINDS:
			if seg.tags.has("circuit_%d" % k):
				kind = int(k)
		seen[kind] = int(seen.get(kind, 0)) + 1
		if kind == SegmentGen.CIRCUIT_HAIRPIN and _longest_min_side(seg) >= 8:
			hairpin_long += 1
		if kind == SegmentGen.CIRCUIT_BOTTLENECK and _has_double_squeeze(seg):
			bottleneck_squeeze += 1
		if kind == SegmentGen.CIRCUIT_CHICANE and _direction_changes(seg) >= 3:
			chicane_kinks += 1
	print("[race] circuit kinds built: %s" % str(seen))
	print("[race] hairpins with a long tight side %d/%d, bottlenecks that squeeze %d/%d, chicanes that kink %d/%d"
		% [hairpin_long, int(seen.get(SegmentGen.CIRCUIT_HAIRPIN, 0)),
		   bottleneck_squeeze, int(seen.get(SegmentGen.CIRCUIT_BOTTLENECK, 0)),
		   chicane_kinks, int(seen.get(SegmentGen.CIRCUIT_CHICANE, 0))])

	for k in SegmentGen.CIRCUIT_KINDS:
		check(int(seen.get(k, 0)) > 0,
			"circuit kind %d is actually built (%d) -- a character that is rolled "
				% [k, int(seen.get(k, 0))]
			+ "and never produced leaves every claim about it true of nothing")
	check(hairpin_long > int(seen.get(SegmentGen.CIRCUIT_HAIRPIN, 0)) / 2,
		"most hairpins really do pin one side at its minimum for a long stretch "
		+ "(%d of %d) -- that unbroken tight inside IS the hairpin, and without "
			% [hairpin_long, int(seen.get(SegmentGen.CIRCUIT_HAIRPIN, 0))]
		+ "it the kind is an oval with a different tag")
	check(bottleneck_squeeze > int(seen.get(SegmentGen.CIRCUIT_BOTTLENECK, 0)) / 2,
		"most bottlenecks squeeze BOTH sides at once somewhere (%d of %d) -- that "
			% [bottleneck_squeeze, int(seen.get(SegmentGen.CIRCUIT_BOTTLENECK, 0))]
		+ "is the property no other kind has, because every other kind leaves a "
		+ "wide line on the opposite rail")
	check(chicane_kinks > int(seen.get(SegmentGen.CIRCUIT_CHICANE, 0)) / 2,
		"and most chicanes reverse three times or more (%d of %d)"
			% [chicane_kinks, int(seen.get(SegmentGen.CIRCUIT_CHICANE, 0))])

# The longest unbroken run of rows where either side is down to RACE_LANE_MIN.
func _longest_min_side(seg) -> int:
	var best := 0
	var run := 0
	for z in seg.length:
		var edge: int = _left_edge_of_infield(seg, z)
		if edge < 0:
			run = 0
			continue
		var right: int = seg.width - 1 - _right_edge_of_infield(seg, z)
		if edge <= SegmentGen.RACE_LANE_MIN or right <= SegmentGen.RACE_LANE_MIN:
			run += 1
			best = maxi(best, run)
		else:
			run = 0
	return best

# A row with both sides at their narrowest at the same time.
func _has_double_squeeze(seg) -> bool:
	for z in seg.length:
		var edge: int = _left_edge_of_infield(seg, z)
		if edge < 0:
			continue
		var right: int = seg.width - 1 - _right_edge_of_infield(seg, z)
		if edge <= SegmentGen.RACE_LANE_MIN and right <= SegmentGen.RACE_LANE_MIN:
			return true
	return false

# How many times the hole reverses direction on its way down.
func _direction_changes(seg) -> int:
	var last := 0
	var changes := 0
	var prev := -1
	for z in seg.length:
		var edge: int = _left_edge_of_infield(seg, z)
		if edge < 0:
			continue
		if prev >= 0 and edge != prev:
			var dir: int = 1 if edge > prev else -1
			if last != 0 and dir != last:
				changes += 1
			last = dir
		prev = edge
	return changes

# Where the hole ENDS on this row, or -1 on a row that is all road.
func _right_edge_of_infield(seg, z: int) -> int:
	for x in range(seg.width - 1, -1, -1):
		if not seg.is_solid(x, z):
			return x
	return -1

# Where the hole starts on this row, or -1 on a row that is all road.
func _left_edge_of_infield(seg, z: int) -> int:
	for x in seg.width:
		if not seg.is_solid(x, z):
			return x
	return -1

# THE ROAD IS SOMETIMES TIGHT AND SOMETIMES WIDE, which is what makes a lap have
# more than one speed in it.
#
# THE MINIMUM ON ITS OWN WAS NEVER THE POINT. Every circuit already had a
# narrowest road and it was 8 m -- seven bus widths -- so nothing on the track
# ever obliged anybody to lift, and the whole shape of the thing was decoration
# you drove past at full throttle. Two numbers matter and neither is the minimum
# alone: how tight it gets, and how much WIDER it gets elsewhere.
#
# ASSERTED AS A RATIO, so it survives the constants being retuned. A track whose
# widest road is three times its narrowest has somewhere to commit and somewhere
# to think; one where they are equal is a corridor whatever its width.
#
# AND THE PINCHES ARE SHORT, which is the other half. A lap held at the minimum
# is not a demanding circuit, it is a long thin one -- the squeeze has to be a
# thing you come out of.
func _the_road_width_varies_enough_to_force_a_lift() -> void:
	var varied := 0
	var long_pinch := 0
	var worst_run := 0
	var tightest := 999
	var widest := 0
	for i in WIDTHS.size() * SEEDS:
		var w: int = int(WIDTHS[i / SEEDS])
		var seg = SegmentGen.race_loop(w, i % SEEDS, (i % SEEDS) % 5)
		var lo := 999
		var hi := 0
		var run := 0
		var longest := 0
		for z in seg.length:
			var runs: Array = _road_runs(seg, z)
			if runs.size() < 2:
				continue
			var pinched := false
			for r in runs:
				var width: int = int(r.y - r.x + 1)
				lo = mini(lo, width)
				hi = maxi(hi, width)
				if width <= SegmentGen.RACE_LANE_PINCH:
					pinched = true
			run = run + 1 if pinched else 0
			longest = maxi(longest, run)
		if lo < 999:
			tightest = mini(tightest, lo)
			widest = maxi(widest, hi)
			if hi >= lo * 3:
				varied += 1
			worst_run = maxi(worst_run, longest)
			# The funnel in and out costs rows either side of the flat bottom, so
			# the budget is the squeeze plus a rate-capped ramp at each end.
			if longest > SegmentGen.RACE_PINCH_ROWS * 4:
				long_pinch += 1
	print("[race] road %d..%d cells; %d of %d circuits vary 3x or more; longest pinch %d rows"
		% [tightest, widest, varied, WIDTHS.size() * SEEDS, worst_run])
	check(varied > WIDTHS.size() * SEEDS / 2,
		"most circuits are at least three times wider somewhere than they are at "
		+ "their tightest (%d of %d) -- a track with one width has one speed, and "
			% [varied, WIDTHS.size() * SEEDS]
		+ "all the shape in the world does not change that")
	check(tightest <= SegmentGen.RACE_LANE_PINCH,
		"and something on these circuits really is down to the pinch (%d cells) -- "
			% tightest
		+ "without it the minimum is a number in a file rather than a corner")
	eq(long_pinch, 0,
		"and no squeeze is held for long (%d over budget, worst %d rows) -- a lap "
			% [long_pinch, worst_run]
		+ "at the minimum is not a demanding circuit, it is a thin one")

# A GATE IS NEVER LONGER THAN A ROAD IS WIDE.
#
# THE ARITHMETIC VERSION OF "ACROSS RATHER THAN ALONG", and it replaces a
# measurement that was right about a straight track and wrong about this one.
#
# The rule used to be "a gate lies on the road's NARROW axis", found by measuring
# the solid run through its middle cell both ways. That works while the road runs
# straight. It stops working the moment the road WANDERS: a gate correctly across
# a wide side road sits in a band that is drifting sideways, so the run along the
# column through it is short, and the rule flagged eighteen perfectly good gates
# for being "along" a road they were across.
#
# So bound the LENGTH instead. A gate crosses a road, and no road on a circuit is
# wider than the widest one the generator can roll -- while the along-the-straight
# bug this rule exists for was twenty-one cells, the width of the canvas. There is
# nothing to tune between those two numbers and nothing about direction to get
# wrong.
func _gate_is_a_crossing(seg, idx: int) -> bool:
	var n := 0
	for entry in seg.checker_cells:
		if int(entry[1]) == idx:
			n += 1
	var widest: int = maxi(SegmentGen.RACE_LANE_MAX,
		SegmentGen.RACE_LANE_MIN + SegmentGen.RACE_OUTER_SWING)
	return n > 0 and n <= widest

# How wide and how deep the enclosed middle is. Measured from the flood rather
# than from the generator's own numbers, so it is a fact about the section.
func _infield_span(seg, outside: Dictionary) -> Vector2i:
	var lo := Vector2i(9999, 9999)
	var hi := Vector2i(-1, -1)
	for z in seg.length:
		for x in seg.width:
			if seg.is_solid(x, z) or outside.has(Vector2i(x, z)):
				continue
			lo.x = mini(lo.x, x)
			lo.y = mini(lo.y, z)
			hi.x = maxi(hi.x, x)
			hi.y = maxi(hi.y, z)
	if hi.x < 0:
		return Vector2i(0, 0)
	return Vector2i(hi.x - lo.x + 1, hi.y - lo.y + 1)

func _count(seg, want_solid: bool) -> int:
	var n := 0
	for z in seg.length:
		for x in seg.width:
			if seg.is_solid(x, z) == want_solid:
				n += 1
	return n

# Every void cell reachable from beyond the canvas, walking through void only.
# What it cannot reach is enclosed, which is the whole claim.
func _flood_void_from_edge(seg) -> Dictionary:
	var seen := {}
	var queue: Array = []
	for x in seg.width:
		for z in [0, seg.length - 1]:
			if not seg.is_solid(x, z):
				queue.append(Vector2i(x, z))
	for z in seg.length:
		for x in [0, seg.width - 1]:
			if not seg.is_solid(x, z):
				queue.append(Vector2i(x, z))
	while queue.size() > 0:
		var at: Vector2i = queue.pop_back()
		if seen.has(at):
			continue
		seen[at] = true
		for step in [Vector2i(1, 0), Vector2i(-1, 0), Vector2i(0, 1), Vector2i(0, -1)]:
			var next: Vector2i = at + step
			if next.x < 0 or next.x >= seg.width or next.y < 0 or next.y >= seg.length:
				continue
			if seen.has(next) or seg.is_solid(next.x, next.y):
				continue
			queue.append(next)
	return seen

func _road_is_connected(seg) -> bool:
	var first := Vector2i(-1, -1)
	var total := 0
	for z in seg.length:
		for x in seg.width:
			if seg.is_solid(x, z):
				total += 1
				if first.x < 0:
					first = Vector2i(x, z)
	if first.x < 0:
		return false
	var seen := {}
	var queue: Array = [first]
	while queue.size() > 0:
		var at: Vector2i = queue.pop_back()
		if seen.has(at):
			continue
		seen[at] = true
		for step in [Vector2i(1, 0), Vector2i(-1, 0), Vector2i(0, 1), Vector2i(0, -1)]:
			var next: Vector2i = at + step
			if next.x < 0 or next.x >= seg.width or next.y < 0 or next.y >= seg.length:
				continue
			if seen.has(next) or not seg.is_solid(next.x, next.y):
				continue
			queue.append(next)
	return seen.size() == total

# THE NARROWEST PIECE OF ROAD ANYWHERE ON THE CIRCUIT.
#
# MEASURED AS RUNS, NOT INWARD FROM THE EDGE. The first version counted solid
# cells starting at x = 0 and x = w-1, which was correct exactly as long as the
# outer rail WAS the canvas edge. The moment the outside was carved that read 0
# on every circuit -- a broken instrument reporting a broken track, on geometry
# that was fine.
#
# A side row is `void road hole road void`, so the question is the width of each
# road RUN. Cap rows are one run across and are skipped: they are the straights,
# and they are as wide as the canvas by construction.
func _thinnest_side(seg) -> int:
	var thinnest := 999
	for z in seg.length:
		var runs: Array = _road_runs(seg, z)
		if runs.size() < 2:
			continue                  # a cap row, or one this claim is not about
		for run in runs:
			thinnest = mini(thinnest, int(run.y - run.x + 1))
	return thinnest if thinnest < 999 else 0

# Maximal runs of solid road across one row, as (from, to) inclusive.
func _road_runs(seg, z: int) -> Array:
	var out: Array = []
	var start := -1
	for x in seg.width:
		if seg.is_solid(x, z):
			if start < 0:
				start = x
		elif start >= 0:
			out.append(Vector2i(start, x - 1))
			start = -1
	if start >= 0:
		out.append(Vector2i(start, seg.width - 1))
	return out

func _signature(seg) -> String:
	var out := "%d:" % seg.length
	var mid_x: int = seg.width / 2
	var mid_z: int = seg.length / 2
	out += "%d," % _thinnest_side(seg)
	var north := 0
	while north < seg.length and seg.is_solid(mid_x, north):
		north += 1
	var west := 0
	while west < seg.width and seg.is_solid(west, mid_z):
		west += 1
	return out + "%d,%d" % [north, west]
